use defineJahiaComponent everywhere
Jahia/luxe-jahia-demo pull request #63
Opened 2024-07-22 10:39 UTC by TimRobertDev

2024-07-24 12:53 UTC, jkevan requested changes

2024-07-24 13:22 UTC, TimRobertDev commented on src/server/views/loginForm/LoginForm.jsx
> +});
Added

2024-07-24 13:22 UTC, TimRobertDev commented on src/server/views/navMenu/NavMenuDefault.jsx
> +});
Adde

2024-07-26 15:55 UTC, jkevan approved these changes

2024-07-26 15:55 UTC, merged